/* Automatically generated by configure - do not modify */
#define ARCH_X86 1
#define TUNECPU generic
#undef HAVE_MMX
#define __CPU__ 586
#define HAVE_BUILTIN_VECTOR 1
#define HAVE_LOCALTIME_R 1
#define HAVE_LRINTF 1
#undef HAVE_VHOOK
#undef CONFIG_ENCODERS
#define CONFIG_DECODERS 1
#undef CONFIG_MPEGAUDIO_HP 
#undef CONFIG_VIDEO4LINUX
#undef CONFIG_DV1394
#define CONFIG_HAVE_DLOPEN 1
#define CONFIG_HAVE_DLFCN 1
#undef CONFIG_AUDIO_OSS
#undef CONFIG_NETWORK
#undef CONFIG_ZLIB
#define HAVE_MALLOC_H 1
#define HAVE_MEMALIGN 1
#define SIMPLE_IDCT 1
#undef CONFIG_FFSERVER
#define CONFIG_RISKY 1
#define restrict __restrict__
