STATIC_LIB_NOINST = libguess.a
SRCS = guess.c		\
       arabic_impl.c	\
       cjk_impl.c	\
       greek_impl.c	\
       hebrew_impl.c	\
       russian_impl.c	\
       turkish_impl.c

include ../../buildsys.mk
