include ../../mk/rules.mk
include ../../mk/objective.mk

gladexmldir = $(pkgdatadir)/glade

OBJECTIVE_DATA = \
	fileinfo.glade:$(gladexmldir) \
	fileinfo_popup.glade:$(gladexmldir) \
	prefswin.glade:$(gladexmldir) \
	addfiles.glade:$(gladexmldir)
