/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_xs_configwin (void);
GtkWidget* create_xs_fileinfowin (void);
GtkWidget* create_xs_sldbfileselector (void);
GtkWidget* create_xs_stilfileselector (void);
GtkWidget* create_xs_hvscpathselector (void);
