LOCALES = be.po \
	  bg.po \
	  br.po \
	  ca.po \
	  cs.po \
	  cy.po \
	  de.po \
	  el.po \
	  es.po \
	  et.po \
	  eu.po \
	  fi.po \
	  fr.po \
	  hi.po \
	  hr.po \
	  hu.po \
	  it.po \
	  ja.po \
	  ka.po \
	  ko.po \
	  lt.po \
	  lv.po \
	  mk.po \
	  nl.po \
	  pl.po \
	  pt_BR.po \
	  ro.po \
	  ru.po \
	  sk.po \
	  sr@Latn.po \
	  sr.po \
	  sv.po \
	  tr.po \
	  uk.po \
	  zh_CN.po \
	  zh_TW.po

include ../buildsys.mk
