/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_config_win (void);
GtkWidget* create_monitor_win (void);
GtkWidget* create_about_win (void);
GtkWidget* create_help_win (void);
