include ${top_srcdir}/mk/rules.mk
include ${top_srcdir}/mk/init.mk

gladexmldir = $(pkgdatadir)/glade

OBJECTIVE_DATA = \
	fileinfo.glade:$(gladexmldir) \
	prefswin.glade:$(gladexmldir)

include ${top_srcdir}/mk/objective.mk
