include ../../../mk/rules.mk
include ../../../mk/init.mk

gladexmldir = $(pkgdatadir)/glade

OBJECTIVE_DATA = \
	fileinfo.glade:$(gladexmldir) \
	prefswin.glade:$(gladexmldir) \
	addfiles.glade:$(gladexmldir)

include ../../../mk/objective.mk
