include ../../../mk/rules.mk
include ../../../mk/init.mk

gladexmldir = $(pkgdatadir)/ui

OBJECTIVE_DATA = \
	carbon-menubar.ui:$(gladexmldir) \
	mainwin.ui:$(gladexmldir) \
	playlist.ui:$(gladexmldir) \
	equalizer.ui:$(gladexmldir)

include ../../../mk/objective.mk
