include ${top_srcdir}/mk/rules.mk
include ${top_srcdir}/mk/init.mk

gladexmldir = $(pkgdatadir)/ui

OBJECTIVE_DATA = \
	mainwin.ui:$(gladexmldir) \
	playlist.ui:$(gladexmldir) \
	equalizer.ui:$(gladexmldir)

include ${top_srcdir}/mk/objective.mk
